#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "material"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = true
    vimcompatible = true
    bootstrap_after = "bootstrap#after"

    enable_neomake = true
    enable_ale = false

        # left sections of statusline
    statusline_left_sections = [
       'winnr',
       'input method',
       'version control info',
       'filename',
       'minor mode lighters'
       'search status'
    ]
    # right sections of statusline
    statusline_right_sections = [
       'syntax checking',
       'major mode',
       'fileformat',
       'whitespace',
       'cursorpos',
       'percentage'
    ]

    # 'winnr' window number
    # 'syntax checking'
    # 'filename' file name
    # 'fileformat' file format
    # 'major mode'
    # 'minor mode lighters'
    # 'cursorpos' cursor position
    # 'percentage' content range
    # 'date' date
    # 'time' time
    # 'whitespace' line number with trailing space at the end
    # 'battery status' battery status
    # 'input method' input method
    # 'search status' search index

[[layers]]
  name = 'colorscheme'

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'ag'

[[layers]]
name = 'ctrlspace'

[[layers]]
name = 'ui'

[[layers]]
name = 'checkers'

[[layers]]
name = 'git'
git-plugin = 'fugitive'

[[layers]]
name = 'VersionControl'

[[layers]]
name = "lang#typescript"

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#html"

[[layers]]
name = "lang#react"

[[layers]]
name = "lang#angular"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "lang#php"

[[layers]]
name = "lang#dockerfile"

[[layers]]
name = "lang#sh"

[[layers]]
name = "lang#toml"
